app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user:
    path: /user
    defaults:   { _controller: AppBundle:Users:AddUser}

accueil:
    path: /index
    defaults: { _controller: AppBundle:Home:Home}